Repository layer5io/meshery-smi-conformance-action, pull requests merged in 2021-05, with the labels that each got.

#2 (CI) fix notify slack on star workflow
  .github/workflows/slack.yml
Labels: area/ci, kind/bug

#5 (CI) update slack.yml
  .github/workflows/slack.yml
Labels: area/ci, kind/bug

#6 [CI] ReleaseDrafter: added project name
  .github/release-drafter.yml
Labels: area/ci

#11 add perf test action
  .github/workflows/smi-conformance.yml
Labels: area/ci, area/performance
